// Generated by CoffeeScript 2.3.2
// assert = (flag) -> if not flag then throw 'assert error!'
var print;

print = console.log;

print('ok');

// f = (a,b) -> a+b  
// #a = 11/0 
// print a
// assert 3 == f 1,2 
// assert 33 == f 11,22

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29mZmVlLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWUuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTtBQUFBLElBQUE7O0FBQ0EsS0FBQSxHQUFRLE9BQU8sQ0FBQzs7QUFDaEIsS0FBQSxDQUFNLElBQU47O0FBRkEiLCJzb3VyY2VzQ29udGVudCI6WyIjIGFzc2VydCA9IChmbGFnKSAtPiBpZiBub3QgZmxhZyB0aGVuIHRocm93ICdhc3NlcnQgZXJyb3IhJ1xyXG5wcmludCA9IGNvbnNvbGUubG9nIFxyXG5wcmludCAnb2snXHJcbiMgZiA9IChhLGIpIC0+IGErYiAgXHJcbiMgI2EgPSAxMS8wIFxyXG4jIHByaW50IGFcclxuIyBhc3NlcnQgMyA9PSBmIDEsMiBcclxuIyBhc3NlcnQgMzMgPT0gZiAxMSwyMlxyXG4iXX0=
//# sourceURL=c:\github\vscode\coffee.coffee