// Generated by CoffeeScript 2.3.2
// assert = (flag) -> if not flag then throw 'assert error!'
// print = console.log 

// f = (a,b) -> a+b  
// #a = 11/0 
// print a
// assert 3 == f 1,2 
// assert 33 == f 11,22


//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29mZmVlLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWUuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSIsInNvdXJjZXNDb250ZW50IjpbIiMgYXNzZXJ0ID0gKGZsYWcpIC0+IGlmIG5vdCBmbGFnIHRoZW4gdGhyb3cgJ2Fzc2VydCBlcnJvciEnXHJcbiMgcHJpbnQgPSBjb25zb2xlLmxvZyBcclxuXHJcbiMgZiA9IChhLGIpIC0+IGErYiAgXHJcbiMgI2EgPSAxMS8wIFxyXG4jIHByaW50IGFcclxuIyBhc3NlcnQgMyA9PSBmIDEsMiBcclxuIyBhc3NlcnQgMzMgPT0gZiAxMSwyMlxyXG4iXX0=
//# sourceURL=c:\github\vscode\coffee.coffee