// Generated by CoffeeScript 2.3.2
var assert, print, substring;

assert = function(flag) {
  if (!flag) {
    throw 'assert error!';
  }
};

print = console.log;

substring = function(left, right, start, stop) {
  if (start === 0 && stop === left.length + right.length) {
    return left + right;
  } else {
    return "a";
  }
};

assert("abcdef" === substring("abc", "def", 0, 6));

assert("a" === substring("abc", "def", 0, 1));

// "abc", "def", 2,5 -> "cde"

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic3Vic3RyaW5nLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJzdWJzdHJpbmcuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxJQUFBLE1BQUEsRUFBQSxLQUFBLEVBQUE7O0FBQUEsTUFBQSxHQUFTLFFBQUEsQ0FBQyxJQUFELENBQUE7RUFBVSxJQUFHLENBQUksSUFBUDtJQUFpQixNQUFNLGdCQUF2Qjs7QUFBVjs7QUFDVCxLQUFBLEdBQVEsT0FBTyxDQUFDOztBQUVoQixTQUFBLEdBQVksUUFBQSxDQUFDLElBQUQsRUFBTyxLQUFQLEVBQWMsS0FBZCxFQUFxQixJQUFyQixDQUFBO0VBQ1IsSUFBRyxLQUFBLEtBQVMsQ0FBVCxJQUFlLElBQUEsS0FBUSxJQUFJLENBQUMsTUFBTCxHQUFjLEtBQUssQ0FBQyxNQUE5QztXQUNJLElBQUEsR0FBSyxNQURUO0dBQUEsTUFBQTtXQUdJLElBSEo7O0FBRFE7O0FBTVosTUFBQSxDQUFPLFFBQUEsS0FBWSxTQUFBLENBQVUsS0FBVixFQUFnQixLQUFoQixFQUF1QixDQUF2QixFQUEwQixDQUExQixDQUFuQjs7QUFDQSxNQUFBLENBQU8sR0FBQSxLQUFPLFNBQUEsQ0FBVSxLQUFWLEVBQWdCLEtBQWhCLEVBQXVCLENBQXZCLEVBQTBCLENBQTFCLENBQWQ7O0FBVkEiLCJzb3VyY2VzQ29udGVudCI6WyJhc3NlcnQgPSAoZmxhZykgLT4gaWYgbm90IGZsYWcgdGhlbiB0aHJvdyAnYXNzZXJ0IGVycm9yISdcclxucHJpbnQgPSBjb25zb2xlLmxvZyBcclxuXHJcbnN1YnN0cmluZyA9IChsZWZ0LCByaWdodCwgc3RhcnQsIHN0b3ApIC0+IFxyXG4gICAgaWYgc3RhcnQgPT0gMCBhbmQgc3RvcCA9PSBsZWZ0Lmxlbmd0aCArIHJpZ2h0Lmxlbmd0aFxyXG4gICAgICAgIGxlZnQrcmlnaHRcclxuICAgIGVsc2VcclxuICAgICAgICBcImFcIlxyXG5cclxuYXNzZXJ0IFwiYWJjZGVmXCIgPT0gc3Vic3RyaW5nIFwiYWJjXCIsXCJkZWZcIiwgMCwgNlxyXG5hc3NlcnQgXCJhXCIgPT0gc3Vic3RyaW5nIFwiYWJjXCIsXCJkZWZcIiwgMCwgMVxyXG5cclxuIyBcImFiY1wiLCBcImRlZlwiLCAyLDUgLT4gXCJjZGVcIiAgIFxyXG4gIl19
//# sourceURL=c:\github\vscode\substring.coffee