// Generated by CoffeeScript 2.3.2
var assert, print, substring;

assert = function(flag) {
  if (!flag) {
    throw 'assert error!';
  }
};

print = console.log;

substring = function(left, right, start, stop) {
  var left_start, left_stop;
  if (start === 0 && stop === left.length + right.length) {
    return left + right;
  } else {
    left_start = start;
    left_stop = stop;
    return left.slice(left_start, left_stop);
  }
};

assert("abcdef" === substring("abc", "def", 0, 6));

assert("a" === substring("abc", "def", 0, 1));

assert("abc" === substring("abc", "def", 0, 3));

// "abc", "def", 2,5 -> "cde"

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic3Vic3RyaW5nLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJzdWJzdHJpbmcuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxJQUFBLE1BQUEsRUFBQSxLQUFBLEVBQUE7O0FBQUEsTUFBQSxHQUFTLFFBQUEsQ0FBQyxJQUFELENBQUE7RUFBVSxJQUFHLENBQUksSUFBUDtJQUFpQixNQUFNLGdCQUF2Qjs7QUFBVjs7QUFDVCxLQUFBLEdBQVEsT0FBTyxDQUFDOztBQUVoQixTQUFBLEdBQVksUUFBQSxDQUFDLElBQUQsRUFBTyxLQUFQLEVBQWMsS0FBZCxFQUFxQixJQUFyQixDQUFBO0FBQ1IsTUFBQSxVQUFBLEVBQUE7RUFBQSxJQUFHLEtBQUEsS0FBUyxDQUFULElBQWUsSUFBQSxLQUFRLElBQUksQ0FBQyxNQUFMLEdBQWMsS0FBSyxDQUFDLE1BQTlDO1dBQ0ksSUFBQSxHQUFLLE1BRFQ7R0FBQSxNQUFBO0lBR0ksVUFBQSxHQUFhO0lBQ2IsU0FBQSxHQUFZO1dBQ1osSUFBSSxDQUFDLEtBQUwsQ0FBVyxVQUFYLEVBQXNCLFNBQXRCLEVBTEo7O0FBRFE7O0FBUVosTUFBQSxDQUFPLFFBQUEsS0FBWSxTQUFBLENBQVUsS0FBVixFQUFnQixLQUFoQixFQUF1QixDQUF2QixFQUEwQixDQUExQixDQUFuQjs7QUFDQSxNQUFBLENBQU8sR0FBQSxLQUFPLFNBQUEsQ0FBVSxLQUFWLEVBQWdCLEtBQWhCLEVBQXVCLENBQXZCLEVBQTBCLENBQTFCLENBQWQ7O0FBQ0EsTUFBQSxDQUFPLEtBQUEsS0FBUyxTQUFBLENBQVUsS0FBVixFQUFnQixLQUFoQixFQUF1QixDQUF2QixFQUEwQixDQUExQixDQUFoQjs7QUFiQSIsInNvdXJjZXNDb250ZW50IjpbImFzc2VydCA9IChmbGFnKSAtPiBpZiBub3QgZmxhZyB0aGVuIHRocm93ICdhc3NlcnQgZXJyb3IhJ1xyXG5wcmludCA9IGNvbnNvbGUubG9nIFxyXG5cclxuc3Vic3RyaW5nID0gKGxlZnQsIHJpZ2h0LCBzdGFydCwgc3RvcCkgLT4gXHJcbiAgICBpZiBzdGFydCA9PSAwIGFuZCBzdG9wID09IGxlZnQubGVuZ3RoICsgcmlnaHQubGVuZ3RoXHJcbiAgICAgICAgbGVmdCtyaWdodFxyXG4gICAgZWxzZVxyXG4gICAgICAgIGxlZnRfc3RhcnQgPSBzdGFydFxyXG4gICAgICAgIGxlZnRfc3RvcCA9IHN0b3BcclxuICAgICAgICBsZWZ0LnNsaWNlIGxlZnRfc3RhcnQsbGVmdF9zdG9wXHJcblxyXG5hc3NlcnQgXCJhYmNkZWZcIiA9PSBzdWJzdHJpbmcgXCJhYmNcIixcImRlZlwiLCAwLCA2XHJcbmFzc2VydCBcImFcIiA9PSBzdWJzdHJpbmcgXCJhYmNcIixcImRlZlwiLCAwLCAxXHJcbmFzc2VydCBcImFiY1wiID09IHN1YnN0cmluZyBcImFiY1wiLFwiZGVmXCIsIDAsIDNcclxuXHJcbiMgXCJhYmNcIiwgXCJkZWZcIiwgMiw1IC0+IFwiY2RlXCIgICBcclxuICJdfQ==
//# sourceURL=c:\github\vscode\substring.coffee